name: "Image Publish Workflow"
on:
  workflow_call:
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      SHA:
        required: true
jobs:
  image-publish:
    runs-on: ubuntu-latest
    name: Image Build and Publish
    steps:
      - uses: actions/checkout@v5
      - run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-learning:${{secrets.SHA}}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-learning:${{secrets.SHA}}
